/* ------------------------------------------------------------------
 * Copyright (C) 1998-2010 PacketVideo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 * -------------------------------------------------------------------
 */
#ifndef MPEG4_ENC_H_INCLUDED
#define MPEG4_ENC_H_INCLUDED


#ifndef OSCL_MEM_H_INCLUDED
#include "oscl_mem.h"
#endif

#ifndef OMX_Component_h
#include "OMX_Component.h"
#endif

#include "mp4_basic.h"

#include <sys/ioctl.h>

#include <binder/MemoryHeapIon.h>
#define SPRD_ION_DEV "/dev/ion"
using namespace android;


#ifndef OSCL_INT64_UTILS_H_INCLUDED
#include "oscl_int64_utils.h"
#endif

#ifndef PV_OMXDEFS_H_INCLUDED
#include "pv_omxdefs.h"
#endif

//#define  SCI_TRACE_LOW   LOGI
#define OMX_MP4ENC_DEBUG //LOGD
#define OMX_MP4ENC_INFO  ALOGI
#define OMX_MP4ENC_ERR  ALOGE

const uint32 DEFAULT_VOL_HEADER_LENGTH = 28;

enum
{
    MODE_H263 = 0,
    MODE_MPEG4
};


class Mpeg4Encoder_OMX
{
    public:

        Mpeg4Encoder_OMX(class OmxComponentBase *pComp);

        OMX_ERRORTYPE Mp4EncInit(OMX_S32 iEncMode,
                                 OMX_VIDEO_PORTDEFINITIONTYPE aInputParam,
                                 OMX_CONFIG_ROTATIONTYPE aInputOrientationType,
                                 OMX_VIDEO_PORTDEFINITIONTYPE aEncodeParam,
                                 OMX_VIDEO_PARAM_MPEG4TYPE aEncodeMpeg4Param,
                                 OMX_VIDEO_PARAM_ERRORCORRECTIONTYPE aErrorCorrection,
                                 OMX_VIDEO_PARAM_BITRATETYPE aRateControlType,
                                 OMX_VIDEO_PARAM_QUANTIZATIONTYPE aQuantType,
                                 OMX_VIDEO_PARAM_MOTIONVECTORTYPE aSearchRange,
                                 OMX_VIDEO_PARAM_INTRAREFRESHTYPE aIntraRefresh,
                                 OMX_VIDEO_PARAM_H263TYPE aH263Type,
                                 OMX_VIDEO_PARAM_PROFILELEVELTYPE* aProfileLevel);


        OMX_BOOL Mp4EncodeVideo(OMX_U8*    aOutBuffer,
                                OMX_U32*   aOutputLength,
                                OMX_BOOL*  aBufferOverRun,
                                OMX_U8**   aOverBufferPointer,
                                OMX_U8*    aInBuffer,
                                 OMX_U8*    aInBuffer_phy,
                                OMX_U32    aInBufSize,
                                OMX_TICKS  aInTimeStamp,
                                OMX_TICKS* aOutTimeStamp,
                                OMX_BOOL*  aSyncFlag);

        OMX_ERRORTYPE Mp4RequestIFrame();
        OMX_BOOL Mp4UpdateBitRate(OMX_U32 aEncodedBitRate);
        OMX_BOOL Mp4UpdateFrameRate(OMX_U32 aEncodeFramerate);
        OMX_BOOL Mp4UpdateIFrameInterval(OMX_U32 aIntraPeriod);

        OMX_ERRORTYPE Mp4EncDeinit();

        OMX_ERRORTYPE Mp4OutBufferSize(OMX_U32 *aMaxVideoFrameSize);

        OMX_BOOL Mp4GetVolHeader(OMX_U8* aOutBuffer, OMX_U32* aOutputLength);

#if PROFILING_ON
        // Profile Statistics
        struct PVEncNodeStats
        {
            OMX_U32 iTotalNumFrames;
            OMX_U32 iNumFramesEncoded;
            OMX_U32 iDuration;  //in milli seconds
            OMX_U32 iTotalEncTime;
            OMX_U32 iColorConversionTime;
        };

        PVEncNodeStats iProfileStats;
#endif

        OmxComponentBase *ipOMXComponent;

    private:

        void CopyToYUVIn(uint8* YUV, int width, int height, int width_16, int height_16);


        OMX_BOOL             iInitialized;
        OMX_COLOR_FORMATTYPE iVideoFormat;

        int     iSrcWidth;
        int     iSrcHeight;
        uint32  iSrcFrameRate;
        OMX_U32 iEncodeMode;
        
        uint8*  iYUVIn;
        uint8*  iYUVIn_phy;	
	sp<MemoryHeapIon> iYUVInPmemHeap;
        uint8*  iVideoIn;
	uint8*  iVideoIn_phy;	

        OMX_U32     iCycleAdaptFrmCnt;    // the frame counter used for auto adapt.
        OMX_U32     iSrcCycleAdaptms;  // the source frame cycle generated by auto adapting.
        OMX_TICKS   iCycleAdaptFirstFrmTime;   // the first frame time used for auto adapt.
        OMX_TICKS   iCycleAdaptInterval;    // the interval between two src frame for auto adapt.
        OMX_TICKS   iLastPicTime;    // the  src_time of the latst  src frame received.
        //
        OMX_TICKS   iNextModTime;    // the expected timestamp of the next frame to be encoded.
        OMX_TICKS   iPreSrcDitherms;  // the dither between src_time and mode_time for the pre frame.
        OMX_BOOL    iFlagAdjustSrcDither;  // when set 1, adjust the timestamp dither of src frame.

	OMX_U32 iTimeIncRes;
	OMX_U32 iTickPerSrc;	


        OMX_U8 iVolHeader[DEFAULT_VOL_HEADER_LENGTH]; /** Vol header */
        OMX_U32 iVolHeaderSize;
        OMX_BOOL iModTimeInitialized;

	OMX_BOOL iEncSycFrame;	
        OMX_U32 iIFrameInterval;	
	OMX_U32 iFrameTypeCounter;
	VOP_PRED_TYPE_E iPredType;	
	OMX_U32 iVBVSize;
	
	OMX_S32 iBs_remain_len;	
	OMX_U32 iBps;
       OMX_U32 iLastFrameBitsEncoded;
       OMX_U32 iAverageFrameBits;
		
	uint8*  iVIDInterBuf;
        uint8*  iEncExtBuf;		
	sp<MemoryHeapIon> iEncExtPmemHeap;
};


#endif ///#ifndef MPEG4_ENC_H_INCLUDED
