#!/bin/make
# THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
# AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
# APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
#
# $D2Tech$ $Rev: 9016 $ $Date: 2009-02-28 07:08:07 +0800 $
#

#
# Always use forward slashes.
# Do not modify this Makefile
#

include $(TOOL_DIR)/def-$(PLATFORM).mk