/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev$ $Date$
 *
 */

#ifndef __XCAP_CMD_GAA_H_
#define __XCAP_CMD_GAA_H_

/*
 * Function prototypes.
 */

int _XCAP_cmdGaaRun(
    XCAP_Cmd      *cmd_ptr,
    _XCAP_XactGaaObj *xact_ptr);

#endif
