/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 17269 $ $Date: 2012-05-29 02:09:52 -0700 (Tue, 29 May 2012) $
 *
 */

#ifndef __ISI_DIAG_H__
#define __ISI_DIAG_H__

ISI_Return ISIDIAG_appMsg(
    ISIP_Message *msg_ptr);
#endif
