/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 29711 $ $Date: 2014-11-06 12:42:22 +0800 (Thu, 06 Nov 2014) $
 */

#ifndef __SIP_SDP_SYNTAX_H_
#define __SIP_SDP_SYNTAX_H_

#define SDP_FIELD_PVERSION    "v"
#define SDP_FIELD_ORIGIN      "o"
#define SDP_FIELD_SESSNAME    "s"
#define SDP_FIELD_INFO        "i"
#define SDP_FIELD_URI         "u"
#define SDP_FIELD_EMAIL       "e"
#define SDP_FIELD_PHONE       "p"
#define SDP_FIELD_CONN        "c"
#define SDP_FIELD_BANDWIDTH   "b"
#define SDP_FIELD_TIME        "t"
#define SDP_FIELD_KEY         "k"
#define SDP_FIELD_ATTR        "a"
#define SDP_FIELD_MEDIA       "m"

#define SDP_VERSION           "0"

#define SDP_NETTYPE_IN        "IN"
#define SDP_NETTYPE_ATM       "ATM"
#define SDP_NETTYPE_LOCAL     "LOCAL"

#define SDP_ADDRTYPE_IP4      "IP4"
#define SDP_ADDRTYPE_IP6      "IP6"
#define SDP_ADDRTYPE_EPN      "EPN"

#define SDP_BW_CT             "CT"
#define SDP_BW_AS             "AS"
#define SDP_BW_RS             "RS"
#define SDP_BW_RR             "RR"
#define SDP_BW_TIAS           "TIAS"

#define SDP_ATTR_RTPMAP       "rtpmap"
#define SDP_ATTR_CAT          "cat"
#define SDP_ATTR_KEYWDS       "keywds"
#define SDP_ATTR_TOOL         "tool"
#define SDP_ATTR_PTIME        "ptime"
#define SDP_ATTR_MAXPTIME     "maxptime"
#define SDP_ATTR_MSRPACM      "msrp-acm"
#define SDP_ATTR_RECVONLY     "recvonly"
#define SDP_ATTR_SENDRECV     "sendrecv"
#define SDP_ATTR_SENDONLY     "sendonly"
#define SDP_ATTR_INACTIVE     "inactive"
#define SDP_ATTR_ORIENT       "orient"
#define SDP_ATTR_TYPE         "type"
#define SDP_ATTR_CHARSET      "charset"
#define SDP_ATTR_SDPLANG      "sdplang"
#define SDP_ATTR_LANG         "lang"
#define SDP_ATTR_FRAMERATE    "framerate"
#define SDP_ATTR_QUALITY      "quality"
#define SDP_ATTR_FMTP         "fmtp"
#define SDP_ATTR_EXTMAP       "extmap"
#define SDP_ATTR_SILENCESUPP  "silenceSupp"
#define SDP_ATTR_RTCP                  "rtcp"
#define SDP_ATTR_T38FAXVERSION         "T38FaxVersion" 
#define SDP_ATTR_T38MAXBITRATE         "T38MaxBitRate"
#define SDP_ATTR_T38FAXFILLBITREMOVAL  "T38FaxFillBitRemoval"
#define SDP_ATTR_T38FAXTRANSCODINGMMR  "T38FaxTranscodingMMR"
#define SDP_ATTR_T38FAXTRANSCODINGJBIG "T38FaxTranscodingJBIG"
#define SDP_ATTR_T38FAXRATEMANAGEMENT  "T38FaxRateManagement"
#define SDP_ATTR_T38FAXMAXBUFFER       "T38FaxMaxBuffer"
#define SDP_ATTR_T38FAXMAXDATAGRAM     "T38FaxMaxDatagram"
#define SDP_ATTR_T38FAXUDPEC           "T38FaxUdpEC"
#define SDP_ATTR_CRYPTO                "crypto"
#define SDP_ATTR_ENCRYPTION            "encryption"
#define SDP_ATTR_PATH                  "path"
#define SDP_ATTR_ACCEPT_TYPES          "accept-types"
#define SDP_ATTR_ACCEPT_WRAPPED_TYPES  "accept-wrapped-types"
#define SDP_ATTR_FILE_SELECTOR         "file-selector"
#define SDP_ATTR_FILE_DISPOSITION      "file-disposition"
#define SDP_ATTR_FILE_TRANSFER_ID      "file-transfer-id"
#define SDP_ATTR_CURR                  "curr"
#define SDP_ATTR_DES                   "des"
#define SDP_ATTR_CONF                  "conf"
#define SDP_ATTR_SETUP                 "setup"
#define SDP_ATTR_FINGERPRINT           "fingerprint"
#define SDP_ATTR_FRAMESIZE             "framesize"
#define SDP_ATTR_TCAP                  "tcap"
#define SDP_ATTR_PCFG                  "pcfg"
#define SDP_ATTR_RTCPFB                "rtcpfb"

#define SDP_MEDIA_IMAGE       "image"
#define SDP_MEDIA_AUDIO       "audio"
#define SDP_MEDIA_VIDEO       "video"
#define SDP_MEDIA_APPL        "application"
#define SDP_MEDIA_MSG         "message"
#define SDP_MEDIA_DATA        "data"
#define SDP_MEDIA_CTRL        "control"

#define SDP_TP_LOCAL          "LOCAL"
#define SDP_TP_RTPAVP         "RTP/AVP"
#define SDP_TP_RTPSAVP        "RTP/SAVP"
#define SDP_TP_RTPAVPF        "RTP/AVPF"
#define SDP_TP_RTPSAVPF       "RTP/SAVPF"
#define SDP_TP_ATMAVP         "ATM/AVP"
#define SDP_TP_UDP            "udp"
#define SDP_TP_TCP            "tcp"
#define SDP_TP_SIP            "sip"
#define SDP_TP_UDPTL          "udptl"
#define SDP_TP_MSRPTCP        "TCP/MSRP"
#define SDP_TP_MSRPTLS        "TCP/TLS/MSRP"

#define SDP_ENCODING_PCMU     "PCMU"
#define SDP_ENCODING_PCMA     "PCMA"
#define SDP_ENCODING_G726     "G726"
#define SDP_ENCODING_G729     "G729"

#define SDP_ON_STR            "on"
#define SDP_OFF_STR           "off" 
#define SDP_NULL_STR          "null" 

#define SDP_PREC_QOS          "qos"
#define SDP_PREC_E2E          "e2e"
#define SDP_PREC_LOCAL        "local"
#define SDP_PREC_REMOTE       "remote"
#define SDP_PREC_NONE         "none"
#define SDP_PREC_SEND         "send"
#define SDP_PREC_RECV         "recv"
#define SDP_PREC_SENDRECV     "sendrecv"
#define SDP_PREC_MANDATORY    "mandatory"
#define SDP_PREC_OPTIONAL     "optional"
#define SDP_PREC_FAILURE      "failure"
#define SDP_PREC_UNKNOWN      "unknown"

#define SDP_HASH_SHA1         "SHA-1"
#define SDP_HASH_SHA224       "SHA-224"
#define SDP_HASH_SHA256       "SHA-256"
#define SDP_HASH_SHA384       "SHA-384"
#define SDP_HASH_SHA512       "SHA-512"
#define SDP_HASH_MD5          "MD5"
#define SDP_HASH_MD2          "MD2"

#define SDP_SETUP_ACTIVE      "active"
#define SDP_SETUP_ACTPASS     "actpass"
#define SDP_SETUP_PASSIVE     "passive"
#endif 
