/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 11817 $ $Date: 2010-04-16 06:43:37 +0800 (五, 16  4月 2010) $
 *
 */

#ifndef _SYSTEM_START_H_
#define _SYSTEM_START_H_

#include <osal.h>

#endif
