#!/bin/make
# THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
# AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
# APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
#
# $D2Tech$ $Rev: 988 $ $Date: 2006-11-03 07:47:08 +0800 (Fri, 03 Nov 2006) $
#

#
# Do not modify this Makefile
#

export MODULE_PREFIX	:=
export MODULE_OUTPUT	:=



# END OF MAKEFILE

