/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 5870 $ $Date: 2008-04-09 13:16:29 -0400 (Wed, 09 Apr 2008) $
 */

#ifndef __TIC_H_
#define __TIC_H_

#include "vhw.h"
#include "tic.h"
#include "osal_types.h"

#endif
