#!/bin/make
# THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
# AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
# APPLIES: "COPYRIGHT 2004 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
#
# $D2Tech$ $Rev: 988 $ $Date: 2006-11-02 18:47:08 -0500 (Thu, 02 Nov 2006) $
#

#
# Always use forward slashes.
# Do not modify this Makefile
#

include $(TOOL_DIR)/def-$(PLATFORM).mk