/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004-2010 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 24329 $ $Date: 2014-01-29 16:01:40 +0800 (Wed, 29 Jan 2014) $
 *
 */
#ifndef __SUPSRV_TASK_H__
#define __SUPSRV_TASK_H__

void SUPSRV_EventsTask(
    void *arg_ptr);

#endif
