/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004-2010 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Revision: 1381 $ $Date: 2006-12-05 14:44:53 -0800 (Tue, 05 Dec 2006) $
 */

#ifndef __VPAD_MUX_HELPER_H_
#define __VPAD_MUX_HELPER_H_

typedef enum {
    VPAD_DATA_TO_IPC,
    VPAD_DATA_FROM_IPC
} VPAD_DataDir;

void _VPAD_muxSwapVprCommEndian(
    VPR_Comm       *vprComm_ptr,
    VPAD_DataDir    dir);

#endif //__VPMD_HELPER_H_
