/*
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE
 * APPLIES: "COPYRIGHT 2004-2007 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"
 *
 * $D2Tech$ $Rev: 18460 $ $Date: 2012-10-17 20:27:18 -0700 (Wed, 17 Oct 2012) $
 *
 */

#ifndef __CSM_UT_CALL_H_
#define __CSM_UT_CALL_H_

UT_Return CSM_UT_call();

UT_Return _CSM_UT_callResourceReady(
    void);

#endif
